In [1]:
import numpy as np

In [17]:
x = np.array([[1,2,3], [4,5,6]], dtype=np.uint32)
x = x.astype(float)
print(x)
print(type(x))
print(x.ndim)
print(x.shape)
print(x.dtype)
print(x.size)

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>
2
(2, 3)
float64
6


In [18]:
x = np.reshape(x, (3,2))
x.shape
print(x)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [26]:
y = np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
x = np.arange(2,6, 0.5)
x

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [33]:
x = np.linspace(2,7)
print(x)

[2.         2.10204082 2.20408163 2.30612245 2.40816327 2.51020408
 2.6122449  2.71428571 2.81632653 2.91836735 3.02040816 3.12244898
 3.2244898  3.32653061 3.42857143 3.53061224 3.63265306 3.73469388
 3.83673469 3.93877551 4.04081633 4.14285714 4.24489796 4.34693878
 4.44897959 4.55102041 4.65306122 4.75510204 4.85714286 4.95918367
 5.06122449 5.16326531 5.26530612 5.36734694 5.46938776 5.57142857
 5.67346939 5.7755102  5.87755102 5.97959184 6.08163265 6.18367347
 6.28571429 6.3877551  6.48979592 6.59183673 6.69387755 6.79591837
 6.89795918 7.        ]


In [35]:
np.random.seed(42)
x = np.random.randint(2, 8)
x = np.random.random(9)
x

array([0.95071431, 0.73199394, 0.59865848, 0.15601864, 0.15599452,
       0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [36]:
np.random.uniform(10,20, size=10)

array([10.20584494, 19.69909852, 18.32442641, 12.12339111, 11.81824967,
       11.8340451 , 13.04242243, 15.24756432, 14.31945019, 12.9122914 ])

In [37]:
np.random.normal(10,20, size=10)

array([-10.25662241,  16.28494665,  -8.16048151, -18.24607403,
        39.31297538,   5.48447399,  11.35056409, -18.49496372,
        -0.88765449,  12.21845179])

In [43]:
np.random.choice([1, 2, 3, 4, 5, 6], size = 20, p=[0.5,0.1,0.1,.1,.1,.1])

array([1, 1, 5, 1, 1, 2, 1, 5, 1, 6, 4, 1, 1, 5, 4, 4, 4, 1, 1, 1])

In [45]:
np.nan
np.inf

inf

In [67]:
x = np.array(range(9)).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
x[:, 1:3]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [68]:
print(x)
x[[1,2, 0], [1,1, 1]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([4, 7, 1])

In [ ]:
print(x)
x[1:3, 1:2]  = [[11], [11]]
print(x)

In [75]:
print(x)
b = x >3
b = np.bitwise_not(b)
print(b)
x[b]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ True  True  True]
 [ True False False]
 [False False False]]


array([0, 1, 2, 3])

In [76]:
x = np.array(range(9)).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
x + 5
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [88]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [90]:
x = np.arange(10)
x[x % 2 != 0]


array([1, 3, 5, 7, 9])

In [96]:
x = np.arange(10)
x[x % 2 != 0] = -1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [101]:
x = np.arange(10).reshape((-1,5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [107]:
np.sum(x, axis=1, keepdims=True)

array([[10],
       [35]])

In [121]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

b[((b > 5) & (b < 10))]

array([7, 7, 9, 9, 8])

In [124]:
arr = np.arange(9).reshape(3,3)
arr[:, [2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [125]:
np.random.uniform(5, 10, size=(5,3))

array([[9.31551713, 8.11649063, 6.65449012],
       [5.31779175, 6.55491161, 6.62591661],
       [8.64803089, 8.18778736, 9.43606371],
       [7.36107463, 5.59797123, 8.56622394],
       [8.80392524, 7.80638599, 8.8548359 ]])