<center>
<h1 style="color: #√;">Curso de programación con Python</h1> 
<h3 style="color: #333333;">SEMANA 3 - EJERCICIOS</h3> 
</center>

<br>


#### Autor: escribir aquí el nombre del autor


#### <font style="color: red;">**IMPORTANTE**: Los ejercicios (excepto el último) deben ser realizados con funciones.</font>

<h2 style="color: #007BC4;">Ejercicio 1 </h2>
<hr style="border: 0.5px solid #007BC4;">

Dada una tabla de precios de fruta almacenada en un diccionario ({nombre_fruta:precio}), escribir un programa que pregunte al usuario por una fruta y por el número de kilos qué desea comprar y muestre por pantalla el precio resultante. Debe tenerse en cuenta lo siguiente:


- El listado de precios se definirá en el programa de forma estática, guardándose en un diccionario:
        
|  Fruta          |   Precio     | 
| :-------------: | :----------: |
|    pera         |    1.25      |
|    manzana      |    1.70      |
|    kiwi         |    2.90      |
|    mandarina    |    1.19      |
|    fresa        |    3.75      |

- En primer lugar se mostrará por pantalla el listado actual de precios.
- Si la fruta que pide el usuario no está en el diccionario de precios, debe mostrarse un mensaje informando de ello.


#### Ejemplos de ejecución:

<pre>
--- Precios para hoy ---
pera              1.25
naranja           1.70
manzana           1.55
kiwi              2.90
mandarina         1.19
fresa             3.75
------------------------

¿Qué fruta quieres? kiwwi
La fruta kiwwi no está disponible.

----------------------------------

--- Precios para hoy ---
pera              1.25
naranja           1.70
manzana           1.55
kiwi              2.90
mandarina         1.19
fresa             3.75
------------------------

¿Qué fruta quieres? kiwi
¿Cuántos kilos? 0.5
0.5 kg de kiwi cuestan 1.45 euros

</pre>



In [ ]:
#Escribe aquí el código de tu solución


<h2 style="color: #007BC4;">Ejercicio 2</h2>
<hr style="border: 0.5px solid #007BC4;">


Escribir un programa que cree conjunto simulando una lista de la compra. El programa debe preguntar el artículo y añadirlo al conjunto, mostrando un mensaje de aviso en caso de que el artículo ya existiese.



#### Ejemplo de ejecución:

<pre>
Introduce un artículo: pan
¿Quieres añadir artículos a la lista (Si/No)? Si
Introduce un artículo: agua
¿Quieres añadir artículos a la lista (Si/No)? Si
Introduce un artículo: leche
¿Quieres añadir artículos a la lista (Si/No)? Si
Introduce un artículo: café
¿Quieres añadir artículos a la lista (Si/No)? No
Artículos añadidos:
leche
agua
pan
café
Número de artículos:  4
</pre>

In [ ]:
#Escribe aquí el código de tu solución



Artículos añadidos:
huevos
pan
leche
Número de artículos: 3


<h2 style="color: #007BC4;">Ejercicio 3</h2>
<hr style="border: 0.5px solid #007BC4;">

Desarrollar un programa en Python que permita adivinar un número (en 10 intentos). 

- El programa generará un número aleatorio entre dos números que pide al usuario:
    - El primer número debe ser mayor que 0 y menor que 50.
    - El segundo número debe ser mayor que el primer número y menor que 500.

A continuación, el programa pedirá números al usuario, y, si el usuario no acierta:
- Indicará si el número a adivinar es mayor o menor que el introducido. 
- Mostrará también el número de intentos restantes. 

El programa termina cuando:
 - El usuario acierta el número: en este caso se indicará en cuantos intentos lo ha acertado
 - Alcanza el limite de intentos sin acertarlo: en este caso se indica al usuario que no lo ha acertado y se muestra el número que se había generado.


Ejemplo de ejecución:

<pre>
Juego de adivinar
-----------------
Introduce dos números y generaré un número al azar entre ellos que tendrás que adivinar. 
 
Introduce el primer número (entre 1 y 50): 1
Introduce el segundo número (entre 2 y 500): 20

He generado un número al azar entre 2 y 20, ver si lo aciertas, tienes 10 intentos.
 
Introduce un número (entre 2 y 20): 10
¡Ohhh! No has acertado. El número es menor que el número que has introducido.
Inténtalo de nuevo, te quedan 9 intentos.

Introduce un número (entre 2 y 20): 5
¡Ohhh! No has acertado. El número es menor que el número que has introducido.
Inténtalo de nuevo, te quedan 8 intentos.

Introduce un número (entre 2 y 20): 3
¡Ohhh! No has acertado. El número es menor que el número que has introducido.
Inténtalo de nuevo, te quedan 7 intentos.

Introduce un número (entre 2 y 20): 2
¡Muy bien! Has acertado el número en 4 intentos.
</pre>

In [5]:
# Realiza tu solución aquí o en un archivo .py independiente


Juego de adivinar
-----------------
Introduce dos números y generaré un número al azar entre ellos que tendrás que adivinar.
He generado un número al azar entre 4 y 5, ver si lo aciertas, tienes 10 intentos.
¡Muy bien! Has acertado el número en 1 intentos.


<h2 style="color: #007BC4;">Ejercicio 4</h2>
<hr style="border: 0.5px solid #007BC4;">

Realizar un programa en Python que permita gestionar las subscripciones de un usuario a diversas plataformas de entretenimiento, utilizando para ello un diccionario.

- El ejercicio parte de un diccionario que contiene el nombre y precio mensual de las subscripciones, formado por la clave (nombre de la plataforma) y el valor (precio mensual):


<pre>
        plataformas = {
        "Netflix": 11.99,
        "HBO": 8.99,       
        "Disney+": 7,
        "DAZN": 9.99,
        "Spotify": 9.99,
        "Apple Music": 9.99,
        "Amazon Prime": 3.99,
        }
</pre>


A continuación, deberá mostrar repetidamente un menú con las siguientes 6 opciones: 

1. Añadir plataforma (permite añadir una nueva plataforma al diccionario)
2. Eliminar plataforma (elimina una plataforma del diccionario)
3. Mostrar plataforma (muestra el precio de una plataforma a partir de su nombre)
4. Listar plataformas (muestra la lista de plataformas y sus precios)
5. Subscribirse n meses a una plataforma (muestra el precio total de la subscripción) 6. Terminar (sale del programa)



#### Ejemplo de ejecución:

<img src="data/ej4_ejecucion.png">

In [8]:
# Realiza tu solución aquí o en un archivo .py independiente



(1) Añadir plataforma
(2) Eliminar plataforma
(3) Mostrar plataforma
(4) Listar plataformas
(5) Subscribirse n meses a una plataforma
(6) Terminar


No existe esa plataforma
(1) Añadir plataforma
(2) Eliminar plataforma
(3) Mostrar plataforma
(4) Listar plataformas
(5) Subscribirse n meses a una plataforma
(6) Terminar
El precio mensual de HBO es: 8.99 €
(1) Añadir plataforma
(2) Eliminar plataforma
(3) Mostrar plataforma
(4) Listar plataformas
(5) Subscribirse n meses a una plataforma
(6) Terminar
El precio de suscripción de 2 meses a HBO es 17.98 €
(1) Añadir plataforma
(2) Eliminar plataforma
(3) Mostrar plataforma
(4) Listar plataformas
(5) Subscribirse n meses a una plataforma
(6) Terminar
Precios mensuales de subscripción
Netflix 11.99
HBO 8.99
Disney+ 7
DAZN 9.99
Spotify 9.99
Apple Music 9.99
Amazon Prime 3.99
(1) Añadir plataforma
(2) Eliminar plataforma
(3) Mostrar plataforma
(4) Listar plataformas
(5) Subscribirse n meses a una plataforma
(6) Terminar


<h2 style="color: #007BC4;">Ejercicio 5</h2>
<hr style="border: 0.5px solid #007BC4;">

El array de numpy <code>gdp_2016</code> contiene el producto interior bruto de países del mundo en el año 2016 en dólares. 



In [2]:
import numpy as np
import pandas as pd

# No hemos visto aún pandas pero no es necesario para el ejercicio,
# tras la siguiente línea, gdp_2016 es un array de numpy 
gdp_2016 = pd.read_csv("data/gdp_pc.csv")["2016"].values

gdp_2016[0:10] # visualizamos los 10 primero valores del array

array([           nan,  1944.11700491,  6454.13537039, 11540.02556108,
                  nan, 16726.72218488, 72399.65347339, 19939.93077479,
        8832.76343477,            nan])

#### Utilizando operaciones lógicas sobre este array, realiza los siguientes ejercicios:


#### 1 -  Crea un nuevo array sin los elementos que son NaN

#### 2 -  Selecciona aquellos PIB que son mayores que 50.000$

array([ 72399.65347339,  50551.5531752 ,  77420.61217204,  63888.73238665,
        58617.97062639,  71472.29596487,  50745.68297711,  74263.99862606,
       102389.43772763, 105420.41423718,  56344.96375629,  50538.6065696 ,
        58790.06140389, 127480.48251099,  54416.61249319,  87832.58651422,
        60932.93003722,  57638.15908799])

#### 3 -  Selecciona aquellos PIB que son menores que 5.000$

array([ 1944.11700491,  6454.13537039, 11540.02556108, 16726.72218488,
       19939.93077479,  8832.76343477, 22661.48853616, 46012.32845157,
       17256.62697044,   777.75285166, 46428.67142458,  2167.64282343,
        1771.01528722,  3579.75679135, 19242.62261574, 22516.81648228,
       12172.06646607, 18066.3006624 ,  8461.53565294,  7234.19524335,
       15123.85001428, 18064.60442722,  8900.76455309, 16956.72477025,
         698.70665573, 44819.48360027, 26851.1685408 , 23193.97411052,
       15529.08410645,  3693.43690912,  3609.37559695,   801.63011974,
        5717.29037095, 14153.92792519,  1521.85721808,  6551.31894829,
       16609.73935418, 15370.63489842, 32707.872887  , 34749.21236327,
       48860.52529211, 10947.71518781, 49029.01483891, 15204.93246446,
       15013.29637986, 13839.96863584,  9175.64442097, 17025.39067931,
       19516.08298373, 31366.86706838, 11242.04751604, 11128.80247428,
       42063.79406454, 36304.85427275, 29743.33742802,  1734.46407452,
      

#### 4 -  Selecciona aquellos PIB que se encuentran entre 40.000 y 50.000

array([46012.32845157, 46428.67142458, 44819.48360027, 48860.52529211,
       49029.01483891, 42063.79406454, 43378.14602882, 41343.29253554,
       42656.2166022 , 46864.95679091, 42281.18818958, 41885.92611335,
       44804.46017271, 48904.55437072])